xflags::xflags! {
    src "./src/flags.rs"

    /// Dev automation for the Korvex workspace.
    cmd xtask {
        /// Check types and lints (cargo check + clippy -D warnings).
        cmd check {}
        /// Run check then the full test suite (unit + integration).
        cmd test {
            /// Optional test filter passed to `cargo test`.
            optional filter: String
        }
        /// Run test then build release artifacts and install the CLI.
        cmd build {
            /// Force reinstall even if already up to date.
            optional -f, --force
        }
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Check(Check),
    Test(Test),
    Build(Build),
}

#[derive(Debug)]
pub struct Check {}

#[derive(Debug)]
pub struct Test {
    pub filter: Option<String>,
}

#[derive(Debug)]
pub struct Build {
    pub force: bool,
}

#[allow(dead_code)]
impl Xtask {
    pub fn from_env_or_exit() -> Self {
        Self::from_env_or_exit_()
    }
    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }
    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
